### ISSUE TITLE
installation failing

### ISSUE THREAD

**Issue by davidsaroff** [holoviz/holoviz#167] opened 2019-03-31 03:40 UTC
I'm trying to install the examples. I follow the instructions at 
http://pyviz.org/installation.html

and fail at
pyviz examples

with 
(pyviz-tutorial) C:\Users\david>pyviz examples
C:\Users\david\Anaconda3\envs\pyviz-tutorial\lib\site-packages\dask\config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
C:\Users\david\Anaconda3\envs\pyviz-tutorial\lib\site-packages\distributed\config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)
Traceback (most recent call last):
  File "C:\Users\david\Anaconda3\envs\pyviz-tutorial\Scripts\pyviz-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\david\Anaconda3\envs\pyviz-tutorial\lib\site-packages\pyviz\__main__.py", line 9, in main
    return pyct.cmd.substitute_main('pyviz',args=args)
  File "C:\Users\david\Anaconda3\envs\pyviz-tutorial\lib\site-packages\pyct\cmd.py", line 445, in substitute_main
    args.func(args) if hasattr(args,'func') else parser.error("must supply command to run")
  File "C:\Users\david\Anaconda3\envs\pyviz-tutorial\lib\site-packages\pyct\cmd.py", line 417, in <lambda>
    egd_parser.set_defaults(func=lambda args: examples(name, args.path, args.verbose, args.use_test_data, args.force))
  File "C:\Users\david\Anaconda3\envs\pyviz-tutorial\lib\site-packages\pyct\cmd.py", line 36, in examples
    copy_examples(name, path, verbose, force)
  File "C:\Users\david\Anaconda3\envs\pyviz-tutorial\lib\site-packages\pyct\cmd.py", line 45, in copy_examples
    raise ValueError("Path %s already exists; please move it away, choose a different path, or use force."%path)
ValueError: Path C:\Users\david\pyviz-examples already exists; please move it away, choose a different path, or use force.

pls help

**Comment by jsignell** [comment] 2019-03-31 14:36
As the error suggests, it seems that you have already got the examples at C:\Users\david\pyviz-examples. If you run `pyviz examples --help`, you will see all the options available for the command:

```
usage: pyviz examples [-h] [--path PATH] [-v] [--force] [--use-test-data]

optional arguments:
  -h, --help       show this help message and exit
  --path PATH      location to place examples and data
  -v, --verbose
  --force          if PATH already exists, force overwrite existing examples
                   if older than source examples. ALSO force any existing data
                   files to be replaced
  --use-test-data  Use data's test files, if any, instead of fetching full
                   data. If test file not in '.data_stubs', fall back to
                   fetching full data.
```

You can use `pyviz examples --force` to overwrite the contents of your exiting pyviz-examples directory or you can use `pyviz examples --path <new_name>` where `<new_name>` is the name of the new directory you want to use to store the examples.

**Comment by davidsaroff** [comment] 2019-04-01 05:52
I follow your instructions. Then I run the notebook
00_Setup.ipynb
 
No graphics are displayed. The first of several error messages is produced by a cell with this content
import holoviews as hv
hv.__version__

The error message is
----
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-c53db599bae4> in <module>()
----> 1 import holoviews as hv
      2 hv.__version__

**Comment by jbednar** [comment] 2019-04-01 13:49
That error indicates that holoviews is not installed in the current environment.  Most likely, you have installed the code in some other environment, and you either need to switch to using that one, or you need to install it in your current environment.  If you're using conda, you can run `conda env list` to see what environments are available.  Then you can do `conda activate name_of_your_envt`, or if you're in Jupyter you can select the kernel using the "Kernel/Change Kernel" menu option.

**Comment by davidsaroff** [comment] 2019-04-02 03:57
I've succeeded in installing pyviz on a ubuntu 18.04, following the instructions in
http://pyviz.org/tutorial/00_Setup.html

trying again in Windows 10, from the Anaconda3 Anaconda Prompt, I follow the instructions in the above tutorial.  Checking that holoview is installed 

(pyviz-tutorial) C:\Users\david\pyviz-examples>conda list
\# packages in environment at C:\Users\david\Anaconda3\envs\pyviz-tutorial:
...
holoviews                 1.11.3                     py_0

still when jupyter notebook is started 
(pyviz-tutorial) C:\Users\david\pyviz-examples>jupyter notebook

and 
tutorial/00_Setup.ipynb
is launched,

the cell containing 

import holoviews as hv
hv.__version__

produces the error 

ModuleNotFoundError                    Traceback (most recent call last)
<ipython-input-1-c53db599bae4> in <module>()
----> 1 import holoviews as hv
      2 hv.__version__

ModuleNotFoundError: No module named 'holoviews'

I don't get it. holoviews appears in the conda list, but isn't seen from the 00_Setup.ipynb notebook. 

Please advise!

**Comment by jbednar** [comment] 2019-04-02 12:04
That still indicates it is not installed in the environment you are actually using.  You can try doing the install commands from within that notebook, which will ensure it's in the same Python.

**Comment by davidsaroff** [comment] 2019-04-02 17:00
Recap:

This is what I try
starting the Anconda Prompt in Windows 10 from the start menu, in that window I execute 
conda create -n pyviz-tutorial python=3.6
conda activate pyviz-tutorial
conda install -c pyviz/label/dev pyviz
pyviz examples
cd pyviz-examples
jupyter notebook

When jupyter starts, I open the tutorial/00_Setup.ipynb
the cell containing 

import holoviews as hv
hv.__version__

fails with 

ModuleNotFoundError: No module named 'holoviews'

Starting over, from the Anaconda Prompt window
(base) C:\Users\david>conda activate pyviz-tutorial
(pyviz-tutorial) C:\Users\david>cd pyviz-examples
(pyviz-tutorial) C:\Users\david\pyviz-examples>jupyter notebook

opening the tutorial/00_Setup.ipynb
I add a cell at the top that contains
!conda list

which shows among many things
holoviews                 1.11.3                     py_0  

Still, running the cell with 

import holoviews as hv

fails in the same way.

Is anyone willing to work with me live on this? zoom URL
https://us04web.zoom.us/j/2012858319

**Comment by jbednar** [comment] 2019-04-02 18:25
The steps before "starting over" do not necessarily ensure that your notebook is using the `pyviz_tutorial` environment.  They *should*, and typically do, but for reasons unknown to me sometimes Jupyter starts up with a different environment by default, and that may be more common on Windows than on other systems that I use more often.  You can normally do Kernel/Change Kernel in the menu to select the correct kernel.  

Secondly, using a ! will not necessarily tell you about the current kernel; IPython's notion of the current environment for running commands like that is not always the same as for running Python. You can see which python command you are actually running (and thus which environment) using code like:

```
import sys
sys.argv[0]
```
On my system, I get `/Users/jbednar/miniconda3/envs/pyviz/lib/python3.7/site-packages/ipykernel_launcher.py`, which indicates I'm in the pyviz environment; you will presumably see something different, in which case, switch kernels.

**Comment by jsignell** [comment] 2019-04-29 15:21
I am closing this as I suspect the issue is not a general pyviz bug. Please keep commenting if you are still working on getting set up.

**Closed as completed by jsignell** 2019-04-29 15:21 UTC
