### ISSUE TITLE
Including an Other Resources section

### ISSUE THREAD

**Issue by kebowen730** [holoviz/holoviz#247] opened 2020-04-07 23:16 UTC
Hey Team,

I was talking with Jim and Jean-Luc and it sounds like adding an Other Resources section to the homepages of the various HoloViz packages might be a good idea. Datashader has a good example with a lot of helpful resources and tutorials: https://datashader.org/#Other-resources 

What does everyone think would be a good way to link these other resources for our other tools?

**Comment by jbednar** [comment] 2020-04-08 22:17
Some of what Datashader currently lists in that section overlaps with the About page, and should thus be removed so that we don't have to maintain the same material twice. What's left after that is:

# Other resources

You can see Datashader in action in the 2019 HoloViz SciPy tutorial (3 hours!), listen to the Open Source Directions episode from July 2019, or see how it is used in many of the projects at examples.pyviz.org.

Some of the original ideas for Datashader were developed under the name Abstract Rendering, which is described in a 2014 SPIE VDA paper.

**Comment by jbednar** [comment] 2020-04-08 22:19
I do think that all our sites should link very prominently to whatever tutorials, videos, etc. are available, because those are often a much better introduction than the actual documentation. If you agree, some questions:

- [ ] Where should such links go?  It should be prominent and unmissable, in my opinion.
- [ ] What wording should we have?  
- [ ] Is there any similar information that should accompany it?

I'd like to get this settled for Datashader.org then have it applied to all HoloViz tool sites.

**Comment by jbednar** [comment] 2020-09-21 15:31
Closing as duplicate of #233 .

**Closed as completed by jbednar** 2020-09-21 15:31 UTC
